### ISSUE TITLE
Using MonthPicker with dynamic values

### ISSUE THREAD

**Issue by mahezer** [vk-lab/react-month-picker-input#11]
Hi! I'm trying to fetch data from an API and use it as default value for MonthPicker. However, when my component re-renders after the API return, the MonthPicker keeps the static value, instead of the returned API value.

Can you help me ?

**Comment by slavakisel** [comment]
@SirFlyann have you upgraded to the latest version? Component now listens to the props update and re-renders if `year` or `month` props are changed

**Comment by mahezer** [comment]
@slavakisel Somehow it started working...
Sorry to bother...
