### ISSUE TITLE
Mode does not work

### ISSUE THREAD

**Issue by muriloebsantos** [vk-lab/react-month-picker-input#14]
First thank you for you component and good job! But I've found a problem, and unfortunately I can't spend time on correcting this right now.

The setting "mode: Component mode. Available are 'normal', 'readOnly' (input cannot be changed, calendar can be opened but selection is disabled), 'calendarOnly' (input cannot be changed and date can be selected only though calendar)" does not work. The behavior is the same for all configurations.

**Comment by slavakisel** [comment]
@muriloebsantos sorry, I could not reproduce this issue. Are you using version `1.2.1` or above?
