### ISSUE TITLE
Digitation issues

### ISSUE THREAD

**Issue by muriloebsantos** [vk-lab/react-month-picker-input#15]
When typing in the component, if you type "06/92' you will get "06-2092'. This is a little strange nowadays. I'd like to get '06-1992'

Also in the example page "https://slavakisel.github.io/react-month-picker-input/" in the last example, "**Assign new year and month**", the component is formatted in "YYYY/MM", but you will not be able to type "2002/06" because you will get "2006/12".

**Comment by slavakisel** [comment]
relates to #22
