### ISSUE TITLE
Set class name attribute

### ISSUE THREAD

**Issue by ChocolateSlayer** [vk-lab/react-month-picker-input#16]
How can I change class name of main input? 
For now I have 
`<input placeholder="MM/YYYY" type="text" value>
`
But I need something like
 `<input class="form__input" placeholder="MM/YYYY" type="text" value>
`
Is this possible to add className attribute or can I solve this another way?

**Comment by slavakisel** [comment]
@ChocolateSlayer thank you for reporting it! In version `1.2.7` it is now possible to add `className`, `size`, `maxLength` and `required` to the `inputProps` property. Example is available: https://skdev.info/react-month-picker-input/
