### ISSUE TITLE
Close on click

### ISSUE THREAD

**Issue by AmauryLiet** [vk-lab/react-month-picker-input#2]
Hi @slavakisel and thanks for the cool lib!

I have a **feature suggestion** for your lib, what do you think of adding an optionnal boolean prop `closeOnClick` to change the behaviour of the calendar on click?

I am posting it here as I am not sure to have time to contribute myself in the short term ;)

Thanks!

**Comment by slavakisel** [comment]
@AmauryLiet Thank you for your suggestion. Sounds great! I'll add it as soon as I have a time

**Comment by ssaurabhsdm** [comment]
IS there any update regarding closeOnClick ?

**Comment by slavakisel** [comment]
@AmauryLiet @ssaurabhsdm Release `v1.1.2` with `closeOnSelect` property (default `false`). It will close calendar when both `year` and `month` are selected
