### ISSUE TITLE
When selecting January, Input won't update at "first time"

### ISSUE THREAD

**Issue by mifas** [vk-lab/react-month-picker-input#20]
DEMO: https://codesandbox.io/s/peaceful-bird-cpfsv

Try to change the Month to "January". It won't update at the first time. But able to change the Other Months. 

Possible cause can be January is equal to 0

https://github.com/slavakisel/react-month-picker-input/blob/66c95072ca8427c7008b8d842dc8e6c151cf1a9a/src/MonthPickerInput.tsx#L80

`update.month` is `0` at first time. And the condition will fail

valid code will be

```js
const month = update.month >= 0 ? update.month : this.state.month
```

**Comment by slavakisel** [comment]
@mifas thank you for reporting it! Fixed and released `1.2.6`
