### ISSUE TITLE
able to navigate through years even after selecting minDate

### ISSUE THREAD

**Issue by yatinburhmi** [vk-lab/react-month-picker-input#40]
In MonthPickerInput even after selecting minDate I am able to navigate through years. This is working fine for maxDate, if I am entering maxDate I am not able to navigate through years after that. The same should happen in minDate also. 

`<MonthPickerInput
          minDate={[lastSixthMonth,lastYear]}
          maxDate={[currentMonth,currentYear]} 
          onChange={function(maskedValue, selectedYear, selectedMonth) {
           updateForm(maskedValue)
          }}
      />`

**Comment by slavakisel** [comment]
@YatinBurhmi thank you for reporting it, will take a look

**Comment by slavakisel** [comment]
@YatinBurhmi this was fixed in the version `1.3.1`, please check it out
