### ISSUE TITLE
January  not showing in pop-up

### ISSUE THREAD

**Issue by pepies** [vk-lab/react-month-picker-input#42]
https://github.com/vk-lab/react-month-picker-input/blob/2eab88a6a2d33cd351674586df9b169d226db9ec/src/calendar/MonthCalendar.tsx#L190

If Month is January, AKA type number of value 0. This ternary is evaluated as undefined. So January wont show. Please fix that. 

for example by testing if number is in range <0,11> not by using ternary operator.

Thanks

**Comment by slavakisel** [comment]
@pepies we've released fix in the version  `1.3.3`. Could you please check if it is working for you now?
