### ISSUE TITLE
Override month name?

### ISSUE THREAD

**Issue by guillermodoghel** [vk-lab/react-month-picker-input#5]
Is there a wat to override MONTHS_NAMES array from MonthPickerInput properties, or to set another locale such as spanish?  ("Ene" instead of "Jan", etc)?

thanks!, this is the best year/month picker I found so far for react! <3

**Comment by slavakisel** [comment]
@guillermodoghel thank you! You can now. I've just published `1.1.3` which allows to either override `i18n` config in props (see [README](https://github.com/slavakisel/react-month-picker-input#i18n-config) and [last example](https://slavakisel.github.io/react-month-picker-input/)) or you can just add `lang="es"` to props if you are fine with [default spanish translations](https://github.com/slavakisel/react-month-picker-input/blob/master/src/i18n.ts#L54)

**Comment by guillermodoghel** [comment]
thanks @slavakisel it works great!
