### ISSUE TITLE
Picker not close without select year & month

### ISSUE THREAD

**Issue by dipeshmali** [vk-lab/react-month-picker-input#6]
Hello sir , i am using react-month-picker-input (v 1.1.2) when i select year & month then picker was close using closeOnSelect property but i want to close it without select any year & month how can i do this.
please help me to solve this problem. you can check the link for better 
understanding ( https://tinytake.s3.amazonaws.com/pulse/dhp-gmail/attachments/8207704/TinyTake04-07-2018-11-49-11.mp4 )
Thank in advance

**Comment by slavakisel** [comment]
@dipeshmali this month picker can be closed by clicking anywhere outside input or calendar, just like other datepicker. Did I answer your question?

**Comment by dipeshmali** [comment]
No sir you haven't gave answer for this question and i would be very thank full if you could give me solution for this problem.Please help out from this issue.

**Comment by RanaAshish** [comment]
@slavakisel Actually month picker is not going to close when we click outside input or calendar. May be we need to attach any event or method with it?

**Comment by slavakisel** [comment]
@RanaAshish I don't think so. It is being closed without issues both on the [examples page](https://slavakisel.github.io/react-month-picker-input/) and in the other projects where I am using it.
