### ISSUE TITLE
Month picker not reset input values (Month/ year)

### ISSUE THREAD

**Issue by ganeshshinde2115** [vk-lab/react-month-picker-input#7]
Hi Team,

I want to reset month/ year props  on clicking some reset button. i have update state while clicking on reset button but only  state properties updated but month picker not changed any values on UI. 

Is any function or any way to reset month / year value in Month picker .

I want to reset month / year on clicking some other function.

Is any solution for reset value / or change values on clicking of function .

![code](https://user-images.githubusercontent.com/41322475/42805688-1ac0d9bc-89ca-11e8-801f-6f87fac2e1d3.png)

**Comment by slavakisel** [comment]
@ganeshshinde2115 hello, please upgrade to version `1.1.5` or `1.1.6`. In the latest version you can assign a new `year` and `month` props to the component to change/reset the date
