### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by lordsonvimal** [vk-lab/react-month-picker-input#75]
When I use react-month-picker-input, npm audit and yarn audit shows vulnerabilities in dependencies of react. This is blocking to use this library. The vulnerability can be fixed on upgrading `react` and `react-dom`. This works on forked repository (https://github.com/lordsonvimal/react-month-picker-input). But I would like to use the original library without any vulnerabilities.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/47841936/175472762-f063f597-fdc3-43cd-80fe-4951487013f1.png">

**Comment by optimify-team** [comment]
@lordsonvimal Hi, thank you for reporting it! We just published [a new version v1.3.9](https://github.com/optimify-studio/react-month-picker-input/releases/tag/v1.3.9) with updated dependencies list. Please let us know if it works for you

**Comment by lordsonvimal** [comment]
> @lordsonvimal Hi, thank you for reporting it! We just published [a new version v1.3.9](https://github.com/optimify-studio/react-month-picker-input/releases/tag/v1.3.9) with updated dependencies list. Please let us know if it works for you

Thanks for quick release. New version fixes the vulnerabilities 👍
