### ISSUE TITLE
selectedMonth and selectedMonth get wrong result

### ISSUE THREAD

**Issue by k8martian** [vk-lab/react-month-picker-input#8]
I copied and paste the code in your example got selectedMonth showing year and selectedYear showing month/year. I believe this is not normal unless I did something wrong. 

And is it compulsory to enforce monthFormat and monthNames just to change the dateFormat? I just need to my change the dateFormat to YY/MM. Thanks for your time.

**Comment by slavakisel** [comment]
@k8martian hello, sorry for the late response. The example in README was a little outdated - I've updated it https://github.com/slavakisel/react-month-picker-input#usage
Also, I've just released version `1.1.6`. It allows to provide a partial i18n object in props, e.g.:
```
<MonthPickerInput i18n={{ dateFormat: { default: 'YYYY/MM' } }} />
```
Please let me know if this is what you are looking for
