### ISSUE TITLE
Remove values dynamically

### ISSUE THREAD

**Issue by francisco4challenge** [vk-lab/react-month-picker-input#9]
Hi, i have 2 inputs, it's a start and a end date, and i have to block changes if start > end and end < start dates.
I do that validation and when it happens i don't update the current value on the state (the year and month values don't change) but the MonthPickerInput state updates none the less. 
I tried to set both to empty strings, null, but the component inner state does not change.
How can i "reset" the values?

**Comment by slavakisel** [comment]
@francisco4challenge hello, sorry for the late reply. I've just released version `1.1.5` which updates component state if new year or month is assigned in props. Please let me know if this is what you are looking for
